apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iuk8rni4s-nodejs 
  janus-idp.io/tekton: iuk8rni4s-nodejs
  backstage.io/kubernetes-id: iuk8rni4s-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iuk8rni4s-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml